url: "https://tamar.cc"
baseurl: "" # the subpath of your site, e.g. /blog
title: "my cozy space" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-feed
  - jekyll-katex
  - jekyll-minifier
  - jekyll/agda

exclude:
  - "*.agdai"
  - "readme.md"
  - "LICENSE"
  - "deps.nix"
  - "flake.nix"
  - "flake.lock"
  - "result"

katex:
  rendering_options:
    throw_error: true

highlighter: rouge

kramdown:
  math_engine: katex
  math_engine_opts:
    throw_on_error: true

sass:
  sourcemap: always
  sass_dir: assets/css

excerpt_separator: <!--more-->
